### ISSUE TITLE
Client unable to connect

### ISSUE THREAD

**Issue by Xia0ben** [jparyani/mumble-server-sandstorm#1]
Hello there =).

I just tried the murmur package you made available through a link on the google group discussion on my own webserver sandstorm installation (with admin rights of course) but after launching it and configuring it to use Murmur's default port 64738 and authorizing all incoming comms on that port, I couldn't get the client to connect (gave it my server's ip adress with the right port). Was I missing something ?

I actually installed murmur manually aside sandstorm with aptitude, and it worked, so I guess I'll use that for now, but I'm definitely interested in your project, as a web interface to control murmur from sandstorm would be super cool !

Keep up the good work ;-).

**Comment by jparyani** [comment]
Unfortunately, this is due to a breaking change in the Sandstorm API (see https://github.com/sandstorm-io/sandstorm/pull/2027). Typically Sandstorm doesn't do breaking changes, but this API was very new and marked as experimental. I'll update this app to use the new API today.

**Comment by jparyani** [comment]
Fixed by 57cea667a8db36116aa8072269d3e4ef468cf7c7. New spk up at https://4trxu2m00nm0akyroavu.oasis.sandstorm.io/.

Thanks for reporting. I'd love to add a better web configuration UI (and it seems a couple already exist for Murmur), but I'm not sure when I'll have time to do so. For now, this is more of a toy app just showing off how IpInterface works inside Sandstorm :)

**Comment by Xia0ben** [comment]
Thanks for your fast answer, gonna test this asap =).
